server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:bank-account-db

springdoc:
  api-docs:
    path: /bank-account-api/v3/api-docs
  swagger-ui:
    path: /bank-account-api/swagger-ui.html


bankAccount:
  params:
    a: 3
    b: 4